### ISSUE TITLE
aci: make `init` function always payable

### ISSUE THREAD

**Issue by davidyuk** [aeternity/aesophia#373]
Seems that this would be correct because when trying to add `payable` modifier to it the compalier rejects with:
```
type_error:14:3: The init function (at line 14, column 3) cannot be payable.
You don't need the 'payable' annotation to be able to attach
funds to the create contract transaction.
```

ACI that I generated before says that `init` is not payable:
```json
        {
          "arguments": [
            {
              "name": "value",
              "type": "string"
            },
            {
              "name": "key",
              "type": "int"
            }
          ],
          "name": "init",
          "payable": false,
          "returns": "StateContract.state",
          "stateful": false
        },
```

related to https://github.com/aeternity/aepp-sdk-js/issues/1436

**Comment by marc0olo** [comment]
absolutely makes sense to fix this here. didn't think about opening the issue here 😅 

thanks @davidyuk!

@ghallak can you fix this?

**Comment by ghallak** [comment]
@davidyuk @marc0olo Do you think that `init` should always be payable even without marking it with the `payable` keyword?

@hanssv Do you know why `init` cannot be payable?

**Comment by hanssv** [comment]
Init payable, that makes no sense whatsoever. What if the contract is non-payable and the init function is payable? We explicitly made it this way to avoid confusion.

**Comment by marc0olo** [comment]
> @davidyuk @marc0olo Do you think that `init` should always be payable even without marking it with the `payable` keyword?

from my understanding `init` is payable by default and it's not required and not even allowed to use the `payable` keyword here. the issue we face here is that we need a special logic in SDK because the `ACI` says that `init` is not payable which is kind of wrong

> Init payable, that makes no sense whatsoever. What if the contract is non-payable and the init function is payable? We explicitly made it this way to avoid confusion.

I really don't understand this now. maybe we have a flaw in general then. `init` seems to be payable by default to me right now, independent of the contract itself.

we have tests in sophia-examples where this contract receives AE in the `init` function to register an oracle:
- https://github.com/aeternity/aepp-sophia-examples/blob/master/contracts/ExchangeOracles/ExchangeOracle.aes

personally I am more confused then ever now regarding this 🤣

**Comment by marc0olo** [comment]
it might be the case that the example contract is "stupid". it's an old relict which I didn't put into question. I just made sure the tests run and restructered the repo back then.

but anyway, at least we now have a discussion how to deal with `payable` and the `init` function.

@hanssv I agree that it's kind of strange to allow a transfer of AE to `init` if the contract itself isn't declared `payable`. but somehow it seems to be possible right now.

other opinions and comments to this? would also like to know what @thepiwo @kenodressel and @dincho think about this behavior

**Comment by hanssv** [comment]
You are not calling init... You are creating a new contract?! Init is never called, so whether it is payable or not have no significance I think 🤔

**Comment by hanssv** [comment]
You can always fund a contract when you create it (don't think of this as init being payable, please... You'll only confuse yourself 😉) payable means you can't transfer tokens to it later (with spend!) Functions that are payable can always receive funds. Nikita has approved the current setup!

**Comment by marc0olo** [comment]
> You are creating a new contract?!

yeah we are creating a new contract here. I think I need to understand the whole purpose of `init` then 😵 

> (don't think of this as init being payable, please... You'll only confuse yourself 😉

yeah, but why not? what's the purpose of `init`? 🙈 

> Functions that are payable can always receive funds

hopefully everybody gets that. at least I am aware of this 😛 

> Nikita has approved the current setup!

🤔

**Comment by radrow** [comment]
The current design of deploying contracts is quite counterintuitive. When you deploy a contract, the initial funds are transfered to it **before init is called**. Therefore, you won't see that in `Call.value` in `init`, but it will be reflected in `Contract.balance`. Since `init` is stripped away after creation, it is impossible to call it using a call transaction or through a remote call. Consequently, `Call.value` in `init` **will always equal 0**. Thus, it makes no sense to make it ever `payable`. If you want to decide on the payability of contract creation, you need to put the `payable` keyword before contract declaration instead.

If you want to have it open for tests though, you can create a separate entrypoint that returns the initial state. Then you can call it from `init`.

**Comment by radrow** [comment]
> what's the purpose of init?

`init` is to define initial `state` of the contract. Nothing more.

**Comment by hanssv** [comment]
> Nevertheless, I tripped on the above several times and I think it would be better to pass the creation value through `init` instead. But that is a hard-fork requiring change, so it should be discussed in the protocol first.

This makes no sense since you are never calling init - or do you just mean that `Call.value` should have the value of `amount` from ContractCreateTx when evaluating init? That makes sense, it would require a hard fork but would be an easy and small fix. It wouldn't make `init` any more `payable` though.

**Comment by marc0olo** [comment]
thanks for the detailed explanation @radrow!

@davidyuk @subhod-i what's your opinion in terms of SDK implementation to cover this? I mean in the SDK it's now "fixed", right? 😅 

not sure if we should open the next topic for a hardfork here and if it's really needed to be changed. after all it's definitely confusing and counterintuitive like Radek said.

independently one thing is certainly important to clarify:
- do we want a contract to be able to receive funds if NOT declared `payable` explicitely?

**Comment by hanssv** [comment]
> * do we want a contract to be able to receive funds if NOT declared `payable` explicitely?

Since you have perfect control over the `ContractCreateTx` you can make sure it does or doesn't recieve funds at creation so no need to worry?!

**Comment by hanssv** [comment]
> not sure if we should open the next topic for a hardfork here and if it's really needed to be changed. after all it's definitely confusing and counterintuitive like Radek said.

I don't agree... But if you start out by thinking that `init` is a function you call, well then I see that you can get confused. Not sure if that is on the protocol though :sweat_smile:

**Comment by marc0olo** [comment]
I think I understood now. let's see how long that lasts 😆

**Comment by UlfNorell** [comment]
FWIW the mistake we wanted to catch with payable/non-payable contracts was not that the owner of the contract forgot what they wanted to do with it, but that users of the contract (coming from Ethereum) thought they could make the contract do stuff by spending to it.

**Comment by hanssv** [comment]
> yes, but don't we want to avoid people being able to do this at all if not explicitly wanted? in our example with the oracle we would have trapped ourselfs, right?

If someone can't manage to not send tokens along with their ContractCreateTx how do we expect them to remember to set the init function as non-payable? Or just send all their tokens to /dev/null and they'd be done with it a lot quicker...

> this is currently possible as it seems.

Yes, that is a feature interaction between payable and oracles. We should probably check that the account which is turned into an oracle is actually payable - this is currently not done. Feel free to make an issue in `aeternity` repo on that one, it is a general thing but it manifests itself for contracts.

**Comment by hanssv** [comment]
> If the contract is not payable then the init shall be marked as not payable too, Thus it fails when a developer tries to send the amount while calling the deploy method.

No, that is an actual use case. I can think of cases where you want to have a contract with initial funds that you can't spend to.

**Comment by marc0olo** [comment]
> No, that is an actual use case. I can think of cases where you want to have a contract with initial funds that you can't spend to.

I think here it comes back to how `init` is interpreted and treated. there are certainly many people that think `init` is the deploy method which also accepts the AE for initializing the contract.

what's the reason `init` is actually not called (though the logic needs to be executed somehow to set initial state, right?!) and AE is transfered before already?

if we assume `init` is called (I know it's not like we expect) then we could declare it as `payable` while the contract itself can still remain not payable.

I know this topic can be kind of annoying. maybe it helps if we understand why `init` actually isn't called. I know the behavior now, but I am not aware of the reasoning behind this

**Comment by hanssv** [comment]
Contracts are created by a completely separate transaction it is called ContractCreateTX - this is the transaction that creates a contract (this includes the contract state tree, storing the contract byte code, creating the contract account and a few other things). As part of contract creation you can also choose wheter to fund the contract or not by stating the amount of tokens the contract should have initially. As part of contract creation the `init` function is called and the result is the initial state - but creating a contract is a lot more than just calling init.

Nowadays you can also create contracts in contract code, but behind the scenes it works the same - a contract is created and as part of that the `init`-function is called. 

If you want to think about contract creation as being a call to `init` feel free to do so - but the `init` funciton is then **implicilty** payable.

**Comment by marc0olo** [comment]
I see I need to be careful with the words I choose:

- it's absolutely clear to me that `ContractCreateTx` involves more than just `init`
- as you said `init` is called as a part of the contract creation

but anyway. I personally feel it is kind of strange that `payable` is irrelevant for `init` but I don't have a strong opinion on it. not sure how others think about this as long as they state their opinion here.

**Comment by UlfNorell** [comment]
The reasoning behind payable is primarily to protect users of a contract from sending tokens to the contract in the wrong way, either by spending to the contract expecting it to run some code, or by calling the wrong endpoint. A secondary motivation is to make sure the contract has control over when it receives tokens and won't need logic to account for surprise tokens.

For neither of these cases was there a clear need to make it possible to restrict funding contracts at creation time. Do you have any example contracts where you are worried that people might be funding the contract by mistake?

**Comment by marc0olo** [comment]
> For neither of these cases was there a clear need to make it possible to restrict funding contracts at creation time. Do you have any example contracts where you are worried that people might be funding the contract by mistake?

I think it's more of a problem with the tooling around that we build for creating contracts. it's pretty easy currently for devs to send AE to a contract which can't handle the funds.

for sure we can say it's the dev's responsibility as a creator of the contract to not run into this issue. I get that point and that's definitely a statement we currently have to say because it is just this way.

not allowing AE to be transferred to a contract unless `init` (or the contract itself, maybe both?!) is declared `payable` explicitly would protect the creator of a contract to fall into this "trap". I think this would be the only reason why we should think about introducing it. if we all think and say that is not necessary I am absolutely fine with that. I already stated that I have no strong opinion on this.

we just recognized this on SDK side as the SDK did checks about `payable` which is correct for all functions except `init` at the moment. correct me if I am talking nonsense @subhod-i 😅 

--------

independently of that I love that we introduced `payable` in general! the reasoning behind that is absolutely valid.

**Comment by hanssv** [comment]
> not allowing AE to be transferred to a contract unless init (or the contract itself, maybe both?!) is declared payable

"maybe both" is just completely wrong as we have covered at least two times above... 

If there is a strong need for `init`/contractCreateTX to be non-payable because the SDK is badly designed - then file an issue for it and we can prioritize it properly. If there isn't at least a semi-plausible case where the mistake is not of the "don't be stupid" kind it wont be prioritized anytime soon - also, it would be consensus breaking.

**Comment by davidyuk** [comment]
Firstly, the issue I rised is not a blocker for sdk. I got the point that `init` function is not actually payable, so I'm fine to leave it as it is.

Initially `payable: true` seemed to be more semantic because I messed it with the abstraction we have in sdk.

**Comment by marc0olo** [comment]
let's close this before we start discussing again :)

if somebody asks about this in the future we can of course always reference this issue 🙊
